export const homeObjOne = {
    id: "about",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Premium Bank",
    headline: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab reprehenderit necessitatibus pariatur consequuntur perspiciatis libero, quam, vero, aspernatur inventore impedit rem praesentium perferendis. Voluptatem quae culpa dolores. Reprehenderit, expedita voluptatem!",
    buttonLabel: "Get started",
    imgStart: false,
    img: require("../../images/svg-1.svg"),
    alt: "car",
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: "courses",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Premium Bank",
    headline: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab reprehenderit necessitatibus pariatur consequuntur perspiciatis libero, quam, vero, aspernatur inventore impedit rem praesentium perferendis. Voluptatem quae culpa dolores. Reprehenderit, expedita voluptatem!",
    buttonLabel: "Get started",
    imgStart: true,
    img: require("../../images/svg-2.svg"),
    alt: "car",
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: "signup",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Premium Bank",
    headline: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab reprehenderit necessitatibus pariatur consequuntur perspiciatis libero, quam, vero, aspernatur inventore impedit rem praesentium perferendis. Voluptatem quae culpa dolores. Reprehenderit, expedita voluptatem!",
    buttonLabel: "Get started",
    imgStart: false,
    img: require("../../images/svg-3.svg"),
    alt: "car",
    dark: true,
    primary: true,
    darkText: false,
};